# Generated by Django 5.1.2 on 2024-11-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_system_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
