# Generated by Django 5.1.2 on 2024-11-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_system_app', '0004_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
