# Generated by Django 5.1.2 on 2024-11-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_system_app', '0005_task_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_google_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
